server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
            uri: "https://github.com/NisaGokdemir/microservice-egitim-config-server.git"
            default-label: "main"
            skip-ssl-validation: true
            username: "NisaGokdemir"
            password: ${GIT_KEY}